### ISSUE TITLE
Quickstart links are broken 

### ISSUE THREAD

**Issue by andreroggeri** [kolenaIO/kolena#391]
Any example [here](https://docs.kolena.io/quickstart/) takes me to a 404 URL in GitHub

**Comment by gordonhart** [comment]
Hi @andreroggeri — thanks for flagging this! Sorry for the broken links. We're in the middle of a reorganization for our 1.0 release next week, and the examples linked from the quickstart now live under [`examples/workflow`](https://github.com/kolenaIO/kolena/tree/trunk/examples/workflow). We will have this resolved shortly 🙂
